### ISSUE TITLE
Editing bug

### ISSUE THREAD

**Issue by threeel** [pelmered/filament-money-field#12]
I think there is a bug while trying to update and view 
so in my 
ProductsResource  i have this
```php
MoneyInput::make('cost_price')->default(0)
                ->currency('EUR')->locale('el_GR')
                ->required(),
MoneyInput::make('list_price')->default(0)
                ->currency('EUR')->locale('el_GR')
                ->required(),
```

on my migrations
```php 
$table->integer('cost_price');
$table->integer('list_price');
```

on my listing table i have this
```php
MoneyColumn::make('cost_price')->default(0)
                    ->currency('EUR')->locale('el_GR'),
MoneyColumn::make('list_price')->default(0)
                    ->currency('EUR')->locale('el_GR')
```

Every time i click edit product the pricehave an appended 2 zeros
then i save
and i go back to the listing
then i edit again and re appends two zeros.

I think it must be a bug

**Comment by pelmered** [comment]
Could you try if this is fixed in `1.2.0-beta`?

**Comment by threeel** [comment]
@pelmered on 1.2.0 seems to be fixed thank you.

**Comment by pelmered** [comment]
@threeel 1.2.0 is now released!
