### ISSUE TITLE
 I can't make it return null

### ISSUE THREAD

**Issue by DevDanielAlvarez** [pelmered/filament-money-field#18]
![image](https://github.com/pelmered/filament-money-field/assets/91484468/7ae502c5-3c29-4d93-a8c1-115e64278870)
Hello, when I leave the Money input empty instead of returning a null (?) it returns an empty string (' '), and I need it to return null and not an empty string.

**Comment by pelmered** [comment]
Yes, it should probably return `null` in that case. I will look into this.

**Comment by pelmered** [comment]
Sorry, for not fixing this yet. I have been really busy the last few weeks. 
I should be able to fix this next week.

**Comment by pelmered** [comment]
@DevDanielAlvarez Sorry for the delay and thank you for the patience. This should now be fixed in `1.2.1`.

**Comment by demianottema** [comment]
Looks like you have fixed the formatting, but this error happens durring the save (resulting in a broken query)
I will supply a simple fix in a PR.

The code works for sure, but i dont know if it is in line with you codestyle. So feel free to change it!

**Comment by pelmered** [comment]
> Looks like you have fixed the formatting, but this error happens durring the save (resulting in a broken query) I will supply a simple fix in a PR.
> 
> The code works for sure, but i dont know if it is in line with you codestyle. So feel free to change it!
> 
> Edit: @pelmered, the PR is submitted. Super simple but does the job! #23

Ah, shit sorry. My bad. 
Thanks for the PR. I added a comment there.

**Comment by pelmered** [comment]
Now in version `1.2.2` this should finally be fixed.
