### ISSUE TITLE
Using in Summarize Problem

### ISSUE THREAD

**Issue by ahmetkocabiyik** [pelmered/filament-money-field#19]
When we use in summerize it not working properly

```php
Tables\Columns\TextColumn::make('product.name')
                ->label("Ürün Adı"),
                Tables\Columns\TextColumn::make("quantity")
                ->label("Adet"),
                MoneyColumn::make("total_price")
                ->label("Fiyat"),

                MoneyColumn::make('total_price')
                    ->summarize(Sum::make())
``` 

<img width="1270" alt="Screenshot 2024-03-31 at 14 35 45" src="https://github.com/pelmered/filament-money-field/assets/8301394/df119c61-8e33-4309-a7e2-506f2ae83804">

**Comment by ahmetkocabiyik** [comment]
```php
MoneyColumn::make("total_price")
                ->label("Fiyat")
                ->summarize(Sum::make()->money("TRY",100,"tr_TR"))
``` 
I chaange code like this problem solved

**Comment by pelmered** [comment]
Yes, I have been looking into this a bit more and that seems like the way to do it: https://filamentphp.com/docs/3.x/tables/summaries#currency-formatting
The only way I can see to avoid that is the include our own summarizers, but that is out of scope for this package.
