### ISSUE TITLE
Cannot parse x.xx to Money. Number parsing failed: U_PARSE_ERROR

### ISSUE THREAD

**Issue by ahmetkocabiyik** [pelmered/filament-money-field#20]
For example when i type 2000, input formatting looks great 2.000. After then I remove last zero so money amount is 200 but it gives an error like below.  On the other hand, when i type 200 directy it works great. 

<img width="1395" alt="Screenshot 2024-04-12 at 09 04 21" src="https://github.com/pelmered/filament-money-field/assets/8301394/8bb60e74-7a73-4b31-8432-f5c1cfea30fd">

**Comment by pelmered** [comment]
Thank you for this report. I will look into this. 
Do you have any special configuration of the field?

**Comment by ahmetkocabiyik** [comment]
No extra special configuration simple like below

```php
MoneyInput::make("amount")
->label("Miktar")
->required(),
```

**Comment by ahmetkocabiyik** [comment]
@pelmered is there any update ?

**Comment by pelmered** [comment]
@ahmetkocabiyik Sorry for the delay and thank you for the patience. This should now be fixed in `1.2.1`.

**Comment by ahmetkocabiyik** [comment]
@pelmered thank you for your great work.
