### ISSUE TITLE
[Bug] live() breaks MoneyInput

### ISSUE THREAD

**Issue by kainiklas** [pelmered/filament-money-field#21]
Affected Version: 1.2.0

Given the following money field definiton:

```php
MoneyInput::make('average_buy_price')
  ->currency('EUR')->locale('de_DE')
  ->live()
```

The currency switches back after blur.

If the env setting `MONEY_USE_INPUT_MASK=true` is set, then it switches almost immediately.

**Comment by kainiklas** [comment]
I opened PR https://github.com/pelmered/filament-money-field/pull/22 to fix the issue.

**Comment by pelmered** [comment]
Thank you for the PR. I merged it, and will make a release soon. There are some other things I want to get into that release as well.
