### ISSUE TITLE
Pelmered\FilamentMoneyField\Forms\Components\MoneyInput::getLabel(): Return value must be of type string, Closure returned

### ISSUE THREAD

**Issue by LucasVieira2902** [pelmered/filament-money-field#32]
The error bellow occurred after upgrading from version 1.3.0 to version 1.3.1:

Pelmered\FilamentMoneyField\Forms\Components\MoneyInput::getLabel(): Return value must be of type string, Closure returned (View: /home/forge/bolsozen.com.br/vendor/filament/forms/resources/views/components/text-input.blade.php) (View: /home/forge/bolsozen.com.br/vendor/filament/forms/resources/views/components/text-input.blade.php) (View: /home/forge/bolsozen.com.br/vendor/filament/forms/resources/views/components/text-input.blade.php) (View: /home/forge/bolsozen.com.br/vendor/filament/forms/resources/views/components/text-input.blade.php) (View: /home/forge/bolsozen.com.br/vendor/filament/forms/resources/views/components/text-input.blade.php) (View: /home/forge/bolsozen.com.br/vendor/filament/forms/resources/views/components/text-input.blade.php) (View: /home/forge/bolsozen.com.br/vendor/filament/forms/resources/views/components/text-input.blade.php)

![image](https://github.com/pelmered/filament-money-field/assets/66380573/00d1beba-dbbf-4ee2-9d5f-2a37efe01384)

**Comment by pelmered** [comment]
Ah, thank you for the report. I will fix this ASAP.

**Comment by pelmered** [comment]
@LucasVieira2902 This should be fixed now in version `1.3.2`.
