### ISSUE TITLE
Currency not supported: TL

### ISSUE THREAD

**Issue by HakanKorkz** [pelmered/filament-money-field#37]
It was very sad to see that the Turkish lira was not supported, will there be any support for that?

**Comment by pelmered** [comment]
I think that should be supported. This package is using MoneyPHP under the hood and from what I can see Turkish lira (code: TRY) is supported. 

Can you show me some code and explain what is not working in more detail?

**Comment by pelmered** [comment]
Did you use the currency code `TL`? I think the correct ISO code is `TRY`. Try that and see if it works.

**Comment by HakanKorkz** [comment]
Yes, you are very right, I missed that detail in my absent-mindedness.
