### ISSUE TITLE
How to remove decimal part when fill data 

### ISSUE THREAD

**Issue by kohaku1907** [pelmered/filament-money-field#38]
Hi bro.
I m trying to create an edit form .
I m using MoneyInput inside Repeater and fill json data to this Repeater with integer . Ex: {'amount': 1000000}
But it always add ",00" to end of input . Ex: 1.000.000,00
My code :

> MoneyInput::make('amount')
> ->label(__('Amount'))
> ->minValue(0)
> ->currency('VND')
> ->locale('vi_VN')
> ->required()

My .env file:

> MONEY_DEFAULT_LOCALE=vi_VN
> MONEY_DEFAULT_CURRENCY=VND
> MONEY_USE_INPUT_MASK=true
> MONEY_UNIT_PLACEMENT=after

**Comment by pelmered** [comment]
Do you want to set this globally, or for just the field? 

To set it globally you can try to set this in your .env file:
```
MONEY_FRACTION_DIGITS=0
```

Setting it on an individual field is currently not supported, but that would be a great addition. I will add that.

**Comment by kohaku1907** [comment]
I think the release version 1.3.2 is not latest source . I checked the config file and there is not exists MONEY_FRACTION_DIGITS .

**Comment by pelmered** [comment]
> I think your release version 1.3.2 is not latest source . I checked the config file and there is not exists MONEY_FRACTION_DIGITS .

Ah, yes. You are right. Sorry about that. 
I will try to get a new version out this weekend.

**Comment by kohaku1907** [comment]
I hope you release a full updated . Thanks a lot

**Comment by pelmered** [comment]
Sorry, about the delay. I had some personal issues and then I had vacation. I will try to resolve this today.

**Comment by pelmered** [comment]
This is now released in `1.4.0`. Sorry for the delay!
