### ISSUE TITLE
minValue not working as expceted

### ISSUE THREAD

**Issue by JFconcept** [pelmered/filament-money-field#43]
**Describe the bug**
Hi, the MinValueRule is not working as expceted, since it's checking for <= instead of < 

**Steps To Reproduce**
The field

MoneyInput::make('budget')
                ->minValue(2500);

results in Error:
The Budget must be at least 25.00. 

**Screenshots**
![Bildschirmfoto 2024-07-02 um 14 39 09](https://github.com/pelmered/filament-money-field/assets/209216/bc287e64-2034-4e4f-aff6-6aec8b65ebba)

**Additional context**
MinValueRule.php - line 28:
if ($minorValue <= $this->min) {
needs to be:
if ($minorValue < $this->min) {

**Comment by holmesadam** [comment]
Pull request created here: https://github.com/pelmered/filament-money-field/pull/47

**Comment by pelmered** [comment]
Fixed in version `1.4.0`
