### ISSUE TITLE
Placement of currency symbol/code on input fields set to none doesn't work

### ISSUE THREAD

**Issue by zajinx** [pelmered/filament-money-field#44]
**Describe the bug**
Placement of currency symbol/code on input fields set to none doesn't work, it still shows up 

**Steps To Reproduce**
- Show the code of your field.
```
MoneyInput::make('budget_value')
                    ->label(trans('cruds.execution.fields.budget_value') )
                    ->default(0)
                    ->live(),
MoneyColumn::make('budget_value')
                    ->label(trans('cruds.execution.fields.budget_value') )
                    ->sortable(),
```
- What changes have you made to your global config?
- Version of:
   - This package 1.3.2
   - Filament 3.2.92
   - PHP 8.3.8
   - Laravel 11.11.1
   - Anything else that you think might be relevant

**Expected behavior and actual behavior**
A clear and concise description of what you expected to happen and what actually happens.

**Screenshots**
<img width="254" alt="image" src="https://github.com/pelmered/filament-money-field/assets/16177818/89f16ff0-d474-4573-8f4e-2226b7f921e2">
<img width="115" alt="image" src="https://github.com/pelmered/filament-money-field/assets/16177818/c6cfc569-a1f1-4f25-9468-2042beb7609a">

**Additional context**

**Comment by pelmered** [comment]
I'm not sure that I understand the problem. You don't want the currency symbol to show at all? If so, you can set `symbolPlacement` to `hidden` in the next version `1.4.0`.
