### ISSUE TITLE
Decimal digits

### ISSUE THREAD

**Issue by tanthammar** [pelmered/filament-money-field#46]
Hej Peter!

I readme nämns decimal digits...
Hittar inget i repo som matchar någon av nämnda features.

https://github.com/pelmered/filament-money-field?tab=readme-ov-file#decimals-and-significant-digits

Decimals and significant digits
The number of decimals and significant digits can be set in the config file. Defaults to 2.

//with input 123456
MONEY_DECIMAL_DIGITS=0 // Gives 0 decimals, e.g. $1,235
MONEY_DECIMAL_DIGITS=2 // Gives 2 decimals, e.g. $1,234.56
For significant digits, use negative values. For example -2 will give you 2 significant digits.

//with input 12345678
MONEY_DECIMAL_DIGITS=-2 // Gives 2 significant digits, e.g. $120,000
MONEY_DECIMAL_DIGITS=-4 // Gives 4 significant digits, e.g. $123,400
This can also be set on a per-field basis.

MoneyInput::make('price')->decimalDigits(0);
MoneyEntry::make('price')->decimalDigits(2);
MoneyColumn::make('price')->decimalDigits(-2);

**Comment by pelmered** [comment]
Hej Tina! 

Ja, det var inte med i den sista taggade releasen. Nu ska det vara löst i `1.4.0` plus en del annat kul :)
