### ISSUE TITLE
Unable to update to latest version

### ISSUE THREAD

**Issue by zajinx** [pelmered/filament-money-field#54]
**Describe the bug**
Unable to update to latest version, it looks like you restricted the package to Laravel 10 only, it worked just fine in the past.

**Steps To Reproduce**
- Show the code of your field.
- What changes have you made to your global config?
Version of:
This package 1.3.2
Filament 3.2.92
PHP 8.3.8
Laravel 11.11.1
Anything else that you think might be relevant

**Expected behavior and actual behavior**
Since version 1.3.2 worked on Laravel 11, i would expect 1.4 to work also

**Screenshots**
<img width="1229" alt="image" src="https://github.com/user-attachments/assets/7533af02-7520-40ab-8387-f588b409da5e">

**Comment by mouradsm** [comment]
Same here =(

**Comment by pelmered** [comment]
Ah, sorry. This was an oversight on my part. New version coming up asap.

**Comment by pelmered** [comment]
This is now fixed in version `1.4.1`
