### ISSUE TITLE
HRK not supported

### ISSUE THREAD

**Issue by mischasigtermans** [pelmered/filament-money-field#73]
For some reason, [HRK](https://gist.github.com/sgraaf/21d5919940844c9f0c12f147ed45953d#file-currencies-json-L395) is not supported.

**Comment by pelmered** [comment]
Unfortunately, it is not so much I can do about that. That is a limitation in the upstream [PHP Money](https://github.com/moneyphp/money) library. 
Here is a list of [currently supported currencies](https://github.com/moneyphp/money/blob/51ebdac0f5337550bcb1876f2e84755da92b56b8/resources/currency.php).

The way forward would be create an issue or PR there. Once that is resolved, it will be supported here as well.
