### ISSUE TITLE
How to implement the cast?

### ISSUE THREAD

**Issue by jinbatsu** [pelmered/filament-money-field#9]
How to cast the value?
Because, the default is saved in database with extra 00.
And in the edit or view page, it is not devided by 100.

I though it is already automated by MoneyInput ?

**Comment by jinbatsu** [comment]
I solved for a moment forced using Attribute Model.

```php
    protected function sampleSalary(): Attribute
    {
        return Attribute::make(
            get: fn (string $value) => $value > 0 ? $value/100 : 0,
        );
    }
```

**Comment by pelmered** [comment]
Great that you found a solution. I should add some documentation for this.

**Comment by jinbatsu** [comment]
OK, thanks.. it means we do not need to force devide 100 in the model anymore.
